name: 'algolia-docs-sync'
description: 'Fetch docs from repo and upload to Algolia Search'
inputs:
  algoliaId:
    description: 'Algolia Application ID'
    required: true
    default: 'QTVPN6XDU8'
  algoliaKey:
    description: 'Algolia Admin Key'
    required: true
    default: ''
  algoliaIndex:
    description: 'Algolia Index'
    required: true
    default: 'opstrace-docs'
runs:
  using: 'node12'
  main: 'dist/index.js'
